[workspace]
resolver = "2"
members = [
    "crates/prv",
    "crates/prv-core",
    "crates/prv-cass",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Mburdo/prv"

[workspace.dependencies]
anyhow = "1"
thiserror = "1"
